package GUI;

import Domain.Order;
import dao.*;
import java.awt.Color;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Sabah Rahal
 */
public class FrmOrders extends javax.swing.JFrame {

    DefaultTableModel model;
    OrderInterface orderDao = new OrderDAOImpOrderDAOImp();
    Order order = new Order(); 
    int xMouse, yMouse;
    

    
    
    public FrmOrders() throws SQLException {
        initComponents();
        String[] titles = {"ID","Client", "Quantity", "Total", "Pay"};
        model = new DefaultTableModel(null, titles);
        tableOrders.setModel(model);
        CleanAddTextField();
        
        //logo tifon
        try {
            ImageIcon img = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("../imagenes/tifon.png")));
            tifonIcon.setIcon(img);
            img = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("../imagenes/add.png")));
            btnAdd.setIcon(img);
            img = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("../imagenes/refresh.png")));
            btnEdit.setIcon(img);
            img = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("../imagenes/bin.png")));
            btnDelete.setIcon(img);
            img = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("../imagenes/clean.png")));
            btnClean.setIcon(img);
            
            
        } catch (IOException ex) {
            ex.printStackTrace(System.out);
        }
        
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPay = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrders = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        txtClient = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPay = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnPayYes = new javax.swing.JRadioButton();
        btnPayNo = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        tifonIcon = new javax.swing.JLabel();
        bar = new javax.swing.JPanel();
        closeIcon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableOrders = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tableOrders.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 12)); // NOI18N
        tableOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableOrders.setFocusable(false);
        tableOrders.getTableHeader().setResizingAllowed(false);
        tableOrders.getTableHeader().setReorderingAllowed(false);
        tableOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableOrders);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 523, 180));

        btnAdd.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusable(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 150, 130, -1));

        btnDelete.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusable(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 230, 130, -1));

        btnClean.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        btnClean.setText("Clean");
        btnClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClean.setFocusable(false);
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });
        getContentPane().add(btnClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 270, 130, -1));

        txtClient.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 12)); // NOI18N
        txtClient.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientActionPerformed(evt);
            }
        });
        getContentPane().add(txtClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 134, -1));

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(217, 217, 217));
        txtId.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 12)); // NOI18N
        txtId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtId.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        txtId.setFocusable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 45, -1));

        jLabel1.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        jLabel1.setText("Client:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        jLabel2.setText("ID order:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txtQuantity.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 12)); // NOI18N
        txtQuantity.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 134, -1));

        jLabel4.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        jLabel4.setText("Quantity:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(217, 217, 217));
        txtTotal.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 12)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTotal.setFocusable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 132, -1));

        jLabel3.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        jLabel3.setText("Total:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txtPay.setEditable(false);
        txtPay.setBackground(new java.awt.Color(217, 217, 217));
        txtPay.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 12)); // NOI18N
        txtPay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPay.setFocusable(false);
        txtPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayActionPerformed(evt);
            }
        });
        getContentPane().add(txtPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 132, -1));

        jLabel5.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        jLabel5.setText("Pay:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        buttonGroupPay.add(btnPayYes);
        btnPayYes.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 12)); // NOI18N
        btnPayYes.setText("Yes");
        btnPayYes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnPayYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        buttonGroupPay.add(btnPayNo);
        btnPayNo.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 12)); // NOI18N
        btnPayNo.setText("No");
        btnPayNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnPayNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(tifonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 100, 98));

        bar.setBackground(new java.awt.Color(255, 255, 255));
        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });

        closeIcon.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 18)); // NOI18N
        closeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeIcon.setText("x");
        closeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addContainerGap(485, Short.MAX_VALUE)
                .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 40));

        jLabel6.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        jLabel6.setText("Tifon App by Sabah Rahal.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 150, 20));

        btnEdit.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        btnEdit.setText("Update");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setFocusable(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Insert
        String client = txtClient.getText();
        int quantity  = parseInt(txtQuantity.getText());
        boolean pay2 = false;  
        if(btnPayYes.isSelected()){
            pay2 = true; 
        }
        else{
            pay2 = false; 
        }
        
        order.setClient(client);
        order.setQuantity(quantity);
        order.setPay(pay2);
        
        //show Total
        String total = String.valueOf(order.calculateTotal(quantity));
        txtTotal.setText(total);
        JOptionPane.showMessageDialog(null, "Your order has been successfully registered. " + '\n' +"Order total:: " + total + "$");
        try { 
            orderDao.insert(order);
            showData();
        } catch (SQLException ex) {
           ex.printStackTrace(System.out);
        }
        
        finally{
            CleanAddTextField();
            
        }
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientActionPerformed

    private void txtPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
            // Update Data
        int id = parseInt(txtId.getText());
        String client = txtClient.getText();
        int quantity  = parseInt(txtQuantity.getText());
        boolean pay; 
//        boolean pay = Boolean.parseBoolean(txtPay.getText());
        order.setId(id);
        order.setClient(client);
        order.setQuantity(quantity);
        
        if(btnPayYes.isSelected()){
            pay = true; 
            order.setPay(pay);
        }
        
        else{
            pay = false; 
            order.setPay(pay);
        }
        
        //show Total
        String total = String.valueOf(order.calculateTotal(quantity));
        txtTotal.setText(total);
        JOptionPane.showMessageDialog(null, "Your order has been successfully updated. " + '\n' +"Order total: " + total + "$");
        try { 
            orderDao.update(order);
            showData();
        } catch (SQLException ex) {
           ex.printStackTrace(System.out);
        }
        
        finally{
            CleanAddTextField();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    //Mouse Clicked Select Event
    private void tableOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrdersMouseClicked
        //Repasar
        if(evt.getClickCount() == 1 ){
            JTable recept = (JTable) evt.getSource();
            txtId.setText(recept.getModel().getValueAt(recept.getSelectedRow(), 0).toString());
            txtClient.setText(recept.getModel().getValueAt(recept.getSelectedRow(), 1).toString());
            txtQuantity.setText(recept.getModel().getValueAt(recept.getSelectedRow(), 2).toString());
            txtTotal.setText(recept.getModel().getValueAt(recept.getSelectedRow(), 3).toString());
            txtPay.setText(recept.getModel().getValueAt(recept.getSelectedRow(), 4).toString());
            if(txtPay.getText().equalsIgnoreCase("Is pay")){
                btnPayYes.setSelected(true);
            }
            else{
                btnPayNo.setSelected(true); 
            }
            showButtons();
        }
        
    }//GEN-LAST:event_tableOrdersMouseClicked
    
    //Delete
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(!txtId.getText().isEmpty()){
            int id = parseInt(txtId.getText());
            order.setId(id);
            try {
                orderDao.delete(order);
                JOptionPane.showMessageDialog(null, "Su orden ha sido borrada exitosamente.");
                CleanAddTextField();
                showData();
            } catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Your order has been successfully deleted.");
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        //cancel btn (Clean)
        CleanAddTextField();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_barMouseDragged

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeIconMouseClicked

    private void closeIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseEntered
        closeIcon.setBackground(Color.red);
    }//GEN-LAST:event_closeIconMouseEntered

    private void closeIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseExited
        closeIcon.setBackground(Color.white);
    }//GEN-LAST:event_closeIconMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmOrders().setVisible(true);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    public void showData() throws SQLException {
        
        //Remove row update (Repasar)
        while(model.getRowCount()>0){
            model.removeRow(0);
        }
        
        //Select Method
        List<Order> orders = orderDao.select();
        Object[] object = new Object[5];
        for (int i = 0; i < orders.size(); i++) {
            object[0] = orders.get(i).getId();
            object[1] = orders.get(i).getClient();
            object[2] = orders.get(i).getQuantity();
            object[3] = orders.get(i).getTotal();
            object[4] = orders.get(i).isPay();
            
            if(object[4].toString().equals("true")){
                object[4] = "Is pay";
            }
            
            else{
                object[4] = "Don't pay";
            }
            
            model.addRow(object);
        }

    }
    
    private void CleanAddTextField(){
        txtId.setText("");
        txtQuantity.setText("");
        txtClient.setText("");
        txtTotal.setText("");
        txtPay.setText("");
        buttonGroupPay.clearSelection();
        
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        
    }
    
    private void showButtons(){
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
    }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JRadioButton btnPayNo;
    private javax.swing.JRadioButton btnPayYes;
    private javax.swing.ButtonGroup buttonGroupPay;
    private javax.swing.JLabel closeIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableOrders;
    private javax.swing.JLabel tifonIcon;
    private javax.swing.JTextField txtClient;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPay;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
